import { PlatformInfo, Platform, UseCaseCategoryInfo, UseCaseCategory } from "./types";

export const PLATFORMS: Record<Platform, PlatformInfo> = {
  claude: {
    id: "claude",
    name: "Claude",
    provider: "Anthropic",
    identity:
      "The meticulous engineer. Lowest hallucination rate among frontier models, highest instruction-following precision, cleanest code output, best long-context document analysis.",
    color: "#D97706",
    promptFormatName: "XML Tags",
    promptFormatTemplate: `<role>You are a [specific role] with expertise in [domain].</role>
<context>[Background information, documents, data]</context>
<task>[Clear, specific instructions for what to produce]</task>
<output_format>[Explicit format: length, structure, tone, examples]</output_format>
<constraints>[Boundaries: what NOT to do, edge cases, quality bar]</constraints>`,
    promptingRules: [
      "Be explicit, not suggestive — Claude follows the letter of the request",
      'Provide motivation ("why") not just commands',
      '"If you are uncertain, flag it explicitly" for analytical tasks',
      'Use positive framing ("Write in flowing prose" instead of "Don\'t use bullet points")',
      "Avoid the word 'think' with Opus 4.5 when extended thinking is off",
      "Start with one-shot examples; escalate to few-shot only if output drifts",
      "For agentic tasks, point to progress files (progress.txt, tests.json, git logs)",
    ],
    rankedStrengths: [
      "Agentic Coding & Software Engineering (80.8% SWE-bench, Opus 4.6)",
      "Precise Instruction Following (best at light edits, minimal changes)",
      "Long-Context Document Analysis (1M tokens with Opus 4.6; 76% MRCR v2)",
      "Low Hallucination Rate (lowest among frontier models)",
      "Enterprise Knowledge Work (1,606 Elo on GDPval-AA; top Finance Agent)",
      "Safety & Alignment (Constitutional AI; Haiku 4.5 most aligned)",
      "Visual Document & Presentation Creation",
      "Parallel Tool Execution & Agent Orchestration",
    ],
    knownWeaknesses: [
      "Weaker on creative ideation from scratch",
      "Abstract mathematical reasoning (GPT-5.2 leads)",
      "Native multimodal processing & Google integration",
      "Ecosystem breadth and plugin availability",
    ],
    hardExclusions: [
      "Freeform brainstorming (ChatGPT stronger)",
      "Abstract pure math",
      "Tasks requiring live web search",
      "Google Workspace integration",
      "Native video/audio processing",
    ],
    models: [
      {
        id: "claude-haiku-4.5",
        platform: "claude",
        name: "Haiku 4.5",
        primaryUseCases: ["Real-time chat", "High-volume inference", "Quick fixes"],
        contextWindow: "200K",
        speed: "fastest",
        costInput: 1,
        costOutput: 5,
        costLabel: "$1 / $5 per 1M tokens",
        strengths: ["Fastest Claude model", "Most aligned model", "Extended thinking", "73.3% SWE-bench"],
        weaknesses: ["Struggles with long-context retention", "Limited deep reasoning"],
        benchmarks: { "SWE-bench": "73.3%" },
        knownBugs: [],
        promptFormat: "xml",
      },
      {
        id: "claude-sonnet-4.5",
        platform: "claude",
        name: "Sonnet 4.5",
        primaryUseCases: ["Daily coding", "Structured analysis", "General knowledge work"],
        contextWindow: "200K",
        speed: "moderate",
        costInput: 3,
        costOutput: 15,
        costLabel: "$3 / $15 per 1M tokens",
        strengths: ["Best balance of speed/intelligence/cost", "Strong multi-step logic", "77.2% SWE-bench"],
        weaknesses: ["Degrades at very long contexts (10.8% at 256K MRCR v2)"],
        benchmarks: { "SWE-bench": "77.2%" },
        knownBugs: [],
        promptFormat: "xml",
      },
      {
        id: "claude-opus-4.5",
        platform: "claude",
        name: "Opus 4.5",
        primaryUseCases: ["Deep code review", "Architecture decisions", "Complex reasoning"],
        contextWindow: "200K",
        speed: "slow",
        costInput: 5,
        costOutput: 25,
        costLabel: "$5 / $25 per 1M tokens",
        strengths: ["Finds bugs lighter models miss", "Effort parameter (low/medium/high)", "~79% SWE-bench"],
        weaknesses: ["Slower and more expensive"],
        benchmarks: { "SWE-bench": "~79%" },
        knownBugs: [],
        promptFormat: "xml",
      },
      {
        id: "claude-opus-4.6",
        platform: "claude",
        name: "Opus 4.6",
        primaryUseCases: ["Enterprise research", "Massive codebase analysis", "Financial analysis", "Agent orchestration"],
        contextWindow: "1M",
        speed: "slow",
        costInput: 7.5,
        costOutput: 37.5,
        costLabel: "Est. $5-10 / $25-50 per 1M tokens",
        strengths: [
          "1M token context window (beta)",
          "128K output tokens",
          "Adaptive thinking",
          "80.8% SWE-bench (highest any frontier model)",
          "1,606 Elo GDPval-AA",
          "Agent Teams in Claude Code",
        ],
        weaknesses: ["Can overengineer solutions", "May spawn unnecessary subagents"],
        benchmarks: { "SWE-bench": "80.8%", "MRCR v2": "76%", "GDPval-AA": "1,606 Elo" },
        knownBugs: [],
        promptFormat: "xml",
      },
    ],
  },

  chatgpt: {
    id: "chatgpt",
    name: "ChatGPT",
    provider: "OpenAI",
    identity:
      "The broadest generalist and creative powerhouse. ~68% market share, widest task coverage, strongest creative writing, leading abstract math performance.",
    color: "#10B981",
    promptFormatName: "CTCO Framework (Markdown)",
    promptFormatTemplate: `CONTEXT:
[Role assignment, background information, domain, relevant data]

TASK:
[Specific, action-oriented instructions]

CONSTRAINTS:
- [Length limits, scope boundaries, what NOT to do]
- [Edge case handling: "If uncertain, say so"]
- [Scope discipline: "Do not expand beyond what is asked"]

OUTPUT FORMAT:
[Exact format specification: JSON, table, prose, numbered list, etc.]
[Tone, audience, style requirements]`,
    promptingRules: [
      "Put critical instructions at the top AND bottom (primacy-recency effect)",
      "Control reasoning effort with reasoning_effort parameter (low/medium/high/xhigh)",
      "Write well-structured prompts to avoid being routed to weaker Instant tier",
      "Enforce scope discipline — ChatGPT tends toward verbosity and task expansion",
      "Use 1-3 few-shot examples instead of verbose instructions",
      "Use markdown formatting (not XML tags)",
      "Start simple, then layer complexity",
    ],
    rankedStrengths: [
      "Creative Writing & Content Generation (strongest creative generator)",
      "Abstract Reasoning & Mathematics (100% AIME 2025; 52.9% ARC-AGI-2)",
      "Professional Knowledge Work Breadth (70.9% GDPval across 44 professions)",
      "Multimodal Vision Understanding (GPT-5.2 Thinking halves vision error rates)",
      "Agentic Coding — SWE-Bench Pro (55.6%)",
      "Ecosystem & Integration Breadth (68% market share)",
      "Long-Context Reasoning (near-100% 4-needle MRCR to 256K)",
      "Science & Graduate-Level Reasoning (93.2% GPQA Diamond with Pro)",
    ],
    knownWeaknesses: [
      "Instruction-following precision (Claude is tighter)",
      'Writing voice naturalness ("logic plateau")',
      "Higher hallucination baseline",
      "Context loss in long real-world conversations",
    ],
    hardExclusions: [],
    models: [
      {
        id: "gpt-5.2-instant",
        platform: "chatgpt",
        name: "GPT-5.2 Instant",
        primaryUseCases: ["Fast everyday tasks", "Drafting", "Translation"],
        contextWindow: "400K",
        speed: "fastest",
        costInput: null,
        costOutput: null,
        costLabel: "Low (subscription bundled)",
        strengths: ["Fastest GPT model", "Good for drafting/summarizing"],
        weaknesses: ["May produce shallow answers on complex topics"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "ctco",
      },
      {
        id: "gpt-5.2-thinking",
        platform: "chatgpt",
        name: "GPT-5.2 Thinking",
        primaryUseCases: ["Multi-step reasoning", "Accuracy-critical tasks"],
        contextWindow: "400K",
        speed: "moderate",
        costInput: null,
        costOutput: null,
        costLabel: "High (subscription bundled)",
        strengths: [
          "52.9% ARC-AGI-2",
          "100% AIME 2025",
          "Near-100% 4-needle MRCR to 256K",
          "Halves vision error rates",
        ],
        weaknesses: ["Expensive", "Verbose intermediate reasoning inflates token costs"],
        benchmarks: { "ARC-AGI-2": "52.9%", "AIME 2025": "100%", MRCR: "near-100% to 256K" },
        knownBugs: [],
        promptFormat: "ctco",
      },
      {
        id: "gpt-5.2-pro",
        platform: "chatgpt",
        name: "GPT-5.2 Pro",
        primaryUseCases: ["Enterprise decision support", "Complex planning"],
        contextWindow: "400K",
        speed: "slowest",
        costInput: null,
        costOutput: null,
        costLabel: "Highest (subscription bundled)",
        strengths: ["54.2% ARC-AGI-2", "93.2% GPQA Diamond", "Resolved open research problem"],
        weaknesses: ["Most expensive", "Longest response times"],
        benchmarks: { "ARC-AGI-2": "54.2%", "GPQA Diamond": "93.2%" },
        knownBugs: [],
        promptFormat: "ctco",
      },
      {
        id: "gpt-4.1",
        platform: "chatgpt",
        name: "GPT-4.1",
        primaryUseCases: ["Coding", "Instruction following", "Structured output"],
        contextWindow: "1M",
        speed: "fast",
        costInput: null,
        costOutput: null,
        costLabel: "Moderate",
        strengths: ["Precise instruction following", "Reliable structured output", "1M context"],
        weaknesses: ["No reasoning capability", "Can't handle multi-step logical chains"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "ctco",
      },
      {
        id: "o3",
        platform: "chatgpt",
        name: "o3",
        primaryUseCases: ["Deep STEM reasoning", "Legal analysis"],
        contextWindow: "200K",
        speed: "slow",
        costInput: null,
        costOutput: null,
        costLabel: "High",
        strengths: ["State-of-the-art Codeforces and SWE-bench", "Deliberate structured approach"],
        weaknesses: ["Slow", "Expensive", "Overkill for conversational/creative tasks"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "ctco",
      },
      {
        id: "o4-mini",
        platform: "chatgpt",
        name: "o4-mini",
        primaryUseCases: ["Fast STEM", "Math", "High-volume reasoning"],
        contextWindow: "200K",
        speed: "fast",
        costInput: null,
        costOutput: null,
        costLabel: "~80% less than o3",
        strengths: ["80% cheaper than o3", "Best AIME math relative to size", "Higher usage limits"],
        weaknesses: ["Narrowly optimized for STEM", "Less capable on open-ended tasks"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "ctco",
      },
    ],
  },

  gemini: {
    id: "gemini",
    name: "Gemini",
    provider: "Google DeepMind",
    identity:
      "The multimodal native and cost-efficiency leader. Only frontier model natively trained on text, image, audio, and video simultaneously. Largest context windows, deepest Google Workspace integration.",
    color: "#3B82F6",
    promptFormatName: "Role + Goal + Constraints + Examples + Output",
    promptFormatTemplate: `ROLE: You are a [specific role] with expertise in [domain].
GOAL: [Clear, measurable success criteria]
CONTEXT: [Data, documents, media files — pass actual media, don't describe it]
CONSTRAINTS:
- [Targeted positive instructions, not blanket negatives]
- [Behavioral guardrails]
EXAMPLES (1-2):
Input: [sample]
Output: [sample in exact target format]
OUTPUT FORMAT: [Explicit schema]`,
    promptingRules: [
      "Do NOT lower the temperature — keep at 1.0 (lowering causes looping)",
      "Place instructions AFTER data for long contexts",
      "Avoid blanket negative constraints — use targeted positives",
      "Restate critical constraints every 3-5 turns in long conversations",
      "Pick one format style (XML or Markdown) and be consistent — don't mix",
      "Pass actual media files, not text descriptions",
      "For coding: route to Flash, NOT Pro (code-deletion bug)",
    ],
    rankedStrengths: [
      "Native Multimodal Processing (text, image, audio, video; 2-hour video processing)",
      "Cost Efficiency at Scale (Flash $0.50/M input; 90% reduction with context caching)",
      "Largest Context Windows (Pro: 2M tokens)",
      "Google Workspace Integration (native Gmail, Docs, Sheets, Calendar, YouTube, Maps)",
      "Coding Performance — Flash (78% SWE-bench Verified, outperforms Pro)",
      "Real-Time Web Access & Research (deep Google Search integration)",
      "Graduate-Level Science & STEM (90.4% GPQA Diamond on Flash)",
      "Speed & Latency (Flash: 600-900 token replies in 2.6-4.1 seconds)",
    ],
    knownWeaknesses: [
      "Pro has documented code-deletion bug",
      "Instruction following precision below Claude",
      "Creative writing voice can feel generic",
      "Ecosystem lock-in (advantages require Google Workspace)",
    ],
    hardExclusions: [],
    models: [
      {
        id: "gemini-3-flash",
        platform: "gemini",
        name: "Gemini 3 Flash",
        primaryUseCases: ["Daily coding", "Fast iteration", "High-volume inference", "Real-time apps"],
        contextWindow: "1M",
        speed: "fastest",
        costInput: 0.5,
        costOutput: 3,
        costLabel: "$0.50 / $3.00 per 1M tokens",
        strengths: [
          "78% SWE-bench (outperforms Pro)",
          "3x faster than Pro",
          "90.4% GPQA Diamond",
          "4 thinking levels (Minimal/Low/Medium/High)",
        ],
        weaknesses: ["Smaller context window than Pro", "May fall short on deepest reasoning"],
        benchmarks: { "SWE-bench": "78%", "GPQA Diamond": "90.4%" },
        knownBugs: [],
        promptFormat: "gemini",
      },
      {
        id: "gemini-3-pro",
        platform: "gemini",
        name: "Gemini 3 Pro",
        primaryUseCases: ["Complex reasoning", "Massive document analysis", "Enterprise research"],
        contextWindow: "2M",
        speed: "moderate",
        costInput: 3,
        costOutput: 10,
        costLabel: "~$2-4 / higher per 1M tokens (tiered)",
        strengths: ["2M token context window", "Native multimodal", "Strong benchmarks across the board"],
        weaknesses: ["Code-deletion bug (deletes unrelated code during edits)"],
        benchmarks: { "SWE-bench": "76.2%" },
        knownBugs: ["Code-deletion bug: deletes large chunks of unrelated code during edits. Use Flash for coding."],
        promptFormat: "gemini",
      },
      {
        id: "gemini-3-pro-deep-think",
        platform: "gemini",
        name: "Gemini 3 Pro + Deep Think",
        primaryUseCases: ["PhD-level STEM", "Open-ended research", "Hardest reasoning problems"],
        contextWindow: "2M",
        speed: "slowest",
        costInput: 3,
        costOutput: 10,
        costLabel: "Same as Pro (higher token usage)",
        strengths: ["Deep deliberation mode", "Competitive with GPT-5.2 Pro on graduate-level science"],
        weaknesses: ["Significantly slower", "Higher effective cost due to extended generation"],
        benchmarks: { "GPQA Diamond": "92%+" },
        knownBugs: ["Inherits Pro code-deletion bug"],
        promptFormat: "gemini",
      },
    ],
  },

  notebooklm: {
    id: "notebooklm",
    name: "NotebookLM",
    provider: "Google Labs",
    identity:
      "The source-grounded research assistant. Works exclusively with user-uploaded materials. Near-zero hallucination by design. Cannot brainstorm, code, create original content, or answer general knowledge questions.",
    color: "#8B5CF6",
    promptFormatName: "Curate → Learn → Act",
    promptFormatTemplate: `ROLE: You are a [analytical role] reviewing the uploaded sources.
TASK: [Specific analytical question grounded in your sources]
FOCUS: [Direct to specific sources, sections, or themes by name]
OUTPUT FORMAT: [summary, table, flashcards, quiz, action items, Audio Overview, slide deck]`,
    promptingRules: [
      "Source quality determines output quality (GIGO)",
      "Use the full 10,000-character prompt limit",
      'Use the "5 Essential Questions" technique instead of long summaries',
      "Prompt for contradictions between sources",
      "Direct it to specific sources by name",
      "Remind user to upload source documents BEFORE sending the prompt",
    ],
    rankedStrengths: [
      "Source-Grounded Accuracy (near-zero hallucination; every response traceable)",
      "Audio Overviews (AI-generated podcast discussions — unique feature)",
      "Deep Research Mode (automated multi-source synthesis from up to 50 sources)",
      "Multi-Format Content Generation (slides, flashcards, quizzes, reports, audio, video)",
      "Privacy & Data Security (never trains on uploaded data)",
      "Learning & Education Tools (personal tutor, probing questions, adaptive explanations)",
    ],
    knownWeaknesses: [
      "CANNOT create original content",
      "CANNOT answer general knowledge questions",
      "CANNOT access the web",
      "CANNOT write or debug code",
      "Shallower analytical reasoning than Claude",
    ],
    hardExclusions: [
      "Creative writing",
      "Brainstorming",
      "Coding",
      "General Q&A",
      "Real-time research",
      "Any task without user-provided source documents",
    ],
    models: [
      {
        id: "notebooklm-free",
        platform: "notebooklm",
        name: "NotebookLM Free",
        primaryUseCases: ["Casual document analysis", "Student research"],
        contextWindow: "50 sources",
        speed: "moderate",
        costInput: 0,
        costOutput: 0,
        costLabel: "Free",
        strengths: ["50 daily chats", "3 Audio Overviews/day", "10 Deep Research/month"],
        weaknesses: ["50-source cap", "Limited features"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "notebooklm",
      },
      {
        id: "notebooklm-plus",
        platform: "notebooklm",
        name: "NotebookLM Plus",
        primaryUseCases: ["Professional document analysis", "Research workflows"],
        contextWindow: "300 sources",
        speed: "moderate",
        costInput: null,
        costOutput: null,
        costLabel: "$19.99/mo",
        strengths: ["500 daily chats", "20 Audio Overviews/day", "20 Deep Research/day", "300 sources"],
        weaknesses: ["Google watermark on outputs"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "notebooklm",
      },
      {
        id: "notebooklm-ultra",
        platform: "notebooklm",
        name: "NotebookLM Ultra",
        primaryUseCases: ["Intensive research", "Client deliverables", "Team workflows"],
        contextWindow: "300+ sources",
        speed: "moderate",
        costInput: null,
        costOutput: null,
        costLabel: "$249.99/mo",
        strengths: ["5,000 daily chats", "200 Audio Overviews/day", "200 Deep Research/day", "Clean branding"],
        weaknesses: ["Expensive — only justified for dedicated research roles"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "notebooklm",
      },
    ],
  },

  perplexity: {
    id: "perplexity",
    name: "Perplexity",
    provider: "Perplexity AI",
    identity:
      "The AI-powered research engine. Combines LLM reasoning with real-time web search and mandatory source citation. 93.9% factuality benchmark. Not a general assistant — a research instrument.",
    color: "#14B8A6",
    promptFormatName: "Scope → Depth → Format → Source Preference",
    promptFormatTemplate: `SCOPE: [Topic, geographic focus, time period, industry]
DEPTH: [Surface / moderate / exhaustive]
FORMAT: [Table, matrix, executive summary, numbered findings]
SOURCE PREFERENCE: [Peer-reviewed / SEC filings / news outlets / specific publications]`,
    promptingRules: [
      "Use search-friendly language with expert terminology",
      "Do NOT include few-shot examples (they trigger searches for example content)",
      'Include time constraints ("from the last 30 days," "Q4 2025")',
      "Specify source types to improve citation quality",
      "Use follow-up questions to drill down iteratively",
    ],
    rankedStrengths: [
      "Real-Time, Citation-Backed Research (93.9% factuality)",
      "Deep Research (agentic multi-source synthesis with parallel crawling)",
      "Multi-Model Flexibility (choose Sonar, Claude, GPT-5, Gemini in one interface)",
      "Competitive Intelligence & Market Analysis",
      "Cost-Efficient API for Search-Augmented Applications (Sonar at $1/M)",
      "Contextual Follow-Up & Thread Continuity",
      "Factuality & Verification (search-first architecture reduces hallucination)",
    ],
    knownWeaknesses: [
      "CANNOT generate creative content",
      "CANNOT write or debug code",
      "CANNOT analyze user-uploaded documents",
      "Limited conversational depth",
      "Citation accuracy not perfect",
      "Struggles with speculative/predictive queries",
    ],
    hardExclusions: [
      "Creative writing",
      "Coding",
      "Document analysis of uploaded files",
      "Tasks requiring original content generation",
      "Speculative / predictive analysis",
    ],
    models: [
      {
        id: "sonar",
        platform: "perplexity",
        name: "Sonar",
        primaryUseCases: ["Quick Q&A", "Fast retrieval", "Lightweight integration"],
        contextWindow: "128K",
        speed: "fastest",
        costInput: 1,
        costOutput: 1,
        costLabel: "$1 / $1 per 1M tokens",
        strengths: ["Cheapest search-augmented model", "Fast cited answers"],
        weaknesses: ["Shallow analysis", "Limited reasoning"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "perplexity",
      },
      {
        id: "sonar-pro",
        platform: "perplexity",
        name: "Sonar Pro",
        primaryUseCases: ["Deep context", "Comprehensive retrieval"],
        contextWindow: "200K",
        speed: "moderate",
        costInput: 3,
        costOutput: 15,
        costLabel: "$3 / $15 per 1M tokens",
        strengths: ["2x more search results", "200K context", "Citation tokens no longer billed"],
        weaknesses: ["Doesn't match reasoning depth of GPT-5.2 or Claude Opus"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "perplexity",
      },
      {
        id: "sonar-reasoning-pro",
        platform: "perplexity",
        name: "Sonar Reasoning Pro",
        primaryUseCases: ["Chain-of-thought analysis", "Complex multi-step questions"],
        contextWindow: "128K",
        speed: "slow",
        costInput: null,
        costOutput: null,
        costLabel: "Higher tier",
        strengths: ["Chain-of-thought over multiple sources", "Comparative analysis"],
        weaknesses: ["Slower", "More expensive", "Overkill for factual lookups"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "perplexity",
      },
      {
        id: "sonar-deep-research",
        platform: "perplexity",
        name: "Sonar Deep Research",
        primaryUseCases: ["In-depth reports", "Hundreds of sources"],
        contextWindow: "Extended",
        speed: "slowest",
        costInput: null,
        costOutput: null,
        costLabel: "~$0.41/complex query",
        strengths: ["Parallel agent crawl", "Hundreds of sources per query", "Long-form synthesis"],
        weaknesses: ["Slow (minutes, not seconds)", "Can misattribute or link outdated sources"],
        benchmarks: {},
        knownBugs: [],
        promptFormat: "perplexity",
      },
    ],
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// USE-CASE REGISTRY — 30 models across 9 categories
// ─────────────────────────────────────────────────────────────────────────────

export const USE_CASE_REGISTRY: Record<UseCaseCategory, UseCaseCategoryInfo> = {
  planning: {
    id: "planning",
    name: "Planning",
    weight: "26%",
    description: "Project planning, roadmapping, OKR setting, architecture decisions, multi-step task orchestration, dependency mapping",
    topModels: [
      {
        rank: 1,
        modelName: "Claude Opus 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best long-horizon planning — lowest hallucination + strongest instruction-following keeps plans grounded and precise",
        strengths: [
          "Follows complex multi-step instructions without drift",
          "Lowest hallucination rate keeps plans factually grounded",
          "1,606 Elo GDPval-AA enterprise benchmark (#1)",
          "Excellent project decomposition and dependency mapping",
          "Best at producing structured, actionable deliverables",
        ],
        weaknesses: ["Slower than Sonnet", "Most expensive Claude tier"],
        bestFor: ["OKR frameworks", "Project roadmaps", "Architecture decisions", "Sprint planning", "Risk assessment docs", "Multi-quarter plans"],
        costLabel: "$5 / $25 per 1M tokens",
        speed: "slow",
        promptTip: "Use XML tags: <goal>, <constraints>, <timeline>, <deliverables>. Add: 'Break this into sequential phases with dependencies and owners.'",
        keyBenchmark: "1,606 Elo GDPval-AA (enterprise knowledge work #1)",
      },
      {
        rank: 2,
        modelName: "o3",
        provider: "OpenAI",
        accessVia: "chatgpt.com / API",
        verdict: "Best deliberate planning — extended reasoning surfaces edge cases and planning gaps lighter models skip over",
        strengths: [
          "Extended deliberation catches planning gaps and hidden risks",
          "Best at multi-constraint optimization",
          "Excellent at identifying what you haven't thought of",
          "Strong for engineering, finance, and ops-heavy planning",
        ],
        weaknesses: ["Slow", "Expensive", "Can over-engineer simple plans"],
        bestFor: ["Engineering roadmaps", "Complex resource allocation", "Risk analysis", "Multi-party coordination", "Constraint-heavy plans"],
        costLabel: "High (API)",
        speed: "slow",
        promptTip: "CTCO format. Set reasoning_effort=high. Always add: 'Before finalizing, identify the 3 biggest risks in this plan and how to mitigate each.'",
        keyBenchmark: "State-of-the-art complex multi-step reasoning",
      },
      {
        rank: 3,
        modelName: "Gemini 3 Pro",
        provider: "Google DeepMind",
        accessVia: "gemini.google.com / API",
        verdict: "Best for planning from large document sets — 2M context ingests entire company wikis, PRDs, and past project histories",
        strengths: [
          "2M token context fits entire company knowledge base",
          "Native Google Workspace integration (Docs, Sheets, Drive)",
          "Can synthesize existing docs into forward-looking plans",
          "Deep Research mode for market/industry background",
        ],
        weaknesses: ["Code-deletion bug (avoid any coding-related plans)", "Instruction following less precise than Claude"],
        bestFor: ["Enterprise planning from large doc libraries", "Google Workspace orgs", "Strategic planning with full historical context", "Multi-document synthesis into plans"],
        costLabel: "~$2-4 / higher per 1M tokens",
        speed: "moderate",
        promptTip: "Place instructions AFTER data for long-context inputs. Restate goals every 3–5 turns. Avoid blanket negative constraints — use targeted positives.",
        keyBenchmark: "2M token context window (largest frontier model)",
      },
      {
        rank: 4,
        modelName: "Claude Sonnet 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best iterative planning workhorse — fast enough for real-time collaboration, smart enough for complex plans",
        strengths: [
          "77.2% SWE-bench — strong structured reasoning",
          "3–5x faster than Opus for rapid iteration",
          "Great for draft → review → refine planning loops",
          "Excellent follow-through on multi-step instructions",
        ],
        weaknesses: ["Degrades at 256K+ context", "Less exhaustive than Opus for deep analysis"],
        bestFor: ["Daily standup prep", "Iterative plan refinement", "Sprint retrospectives", "Quick planning docs", "Agenda creation"],
        costLabel: "$3 / $15 per 1M tokens",
        speed: "moderate",
        promptTip: "Same XML format as Opus but faster. Ideal for rapid 'draft → review → refine' planning loops with a human in the loop.",
        keyBenchmark: "77.2% SWE-bench Verified",
      },
    ],
    workflowTip: "Perplexity Deep Research for background context → Claude Opus 4.5 to build the structured plan → Claude Sonnet 4.5 for iterative daily refinement.",
  },

  research: {
    id: "research",
    name: "Research",
    weight: "16%",
    description: "Market research, competitive intelligence, literature review, due diligence, fact-finding with mandatory citations",
    topModels: [
      {
        rank: 1,
        modelName: "Perplexity Sonar Deep Research",
        provider: "Perplexity AI",
        accessVia: "perplexity.ai / API",
        verdict: "Best autonomous research agent — parallel-crawls hundreds of sources and synthesizes with mandatory, traceable citations",
        strengths: [
          "Parallel agent crawl across hundreds of sources per query",
          "Mandatory citations for every claim (93.9% factuality)",
          "Autonomous multi-step research without hand-holding",
          "Best for competitive intelligence and market deep-dives",
        ],
        weaknesses: ["Slow — minutes per query", "Can misattribute or link outdated sources", "Not for creative synthesis"],
        bestFor: ["Market research", "Competitive intelligence", "Due diligence", "Literature reviews", "Investor research", "Industry landscaping"],
        costLabel: "~$0.41 per complex query",
        speed: "slowest",
        promptTip: "Structure as: SCOPE (topic, geography, time period) → DEPTH (exhaustive) → FORMAT (numbered findings, executive summary) → SOURCE PREFERENCE (peer-reviewed / SEC filings / news).",
        keyBenchmark: "93.9% factuality; hundreds of sources per query",
      },
      {
        rank: 2,
        modelName: "Gemini 3 Pro (Deep Research mode)",
        provider: "Google DeepMind",
        accessVia: "gemini.google.com",
        verdict: "Best Google-native research — integrates Search, Scholar, YouTube, and your Drive data for uniquely comprehensive synthesis",
        strengths: [
          "Google Search + Scholar + YouTube integration",
          "Can pull from your Google Drive and Gmail for company context",
          "2M token context for massive literature synthesis",
          "Generates audio overview summaries of research",
        ],
        weaknesses: ["Slower than Sonar for live web crawling", "Less citation granularity than Perplexity", "Requires Google account"],
        bestFor: ["Academic research", "Google Workspace orgs", "YouTube/media content research", "Research that needs both web + internal company docs"],
        costLabel: "~$2-4 / higher per 1M tokens",
        speed: "slow",
        promptTip: "Upload relevant internal docs to Drive first. Activate Deep Research mode. Specify: 'Include publications from the last 12 months. Prioritize primary sources.'",
        keyBenchmark: "2M context; Google Search + Scholar + Drive integration",
      },
      {
        rank: 3,
        modelName: "NotebookLM Plus",
        provider: "Google Labs",
        accessVia: "notebooklm.google.com",
        verdict: "Best for synthesizing your own document library — near-zero hallucination because it only uses what you upload",
        strengths: [
          "Near-zero hallucination (source-grounded only)",
          "Every claim fully traceable to uploaded source",
          "300 source capacity per notebook",
          "Audio Overview: AI-generated podcast discussion of your docs",
          "Never trains on your uploaded data",
        ],
        weaknesses: ["Cannot access the web", "Cannot generate original content", "Shallower reasoning than Claude"],
        bestFor: ["Internal doc synthesis", "Research memos from PDFs", "Academic paper review", "Client report synthesis", "Private proprietary data analysis"],
        costLabel: "$19.99/month",
        speed: "moderate",
        promptTip: "Upload all sources first. Use the '5 Essential Questions' technique — ask it to generate 5 probing questions that unlock deep understanding of the material before diving in.",
        keyBenchmark: "Near-zero hallucination; every claim source-traceable",
      },
      {
        rank: 4,
        modelName: "Perplexity Sonar Pro",
        provider: "Perplexity AI",
        accessVia: "perplexity.ai / API",
        verdict: "Best fast cited research — 2x more search results than base Sonar with 200K context for real-time intelligence",
        strengths: [
          "2x more search results than base Sonar",
          "200K context window for long synthesis threads",
          "Citation tokens no longer billed separately",
          "Real-time web access with high factuality",
        ],
        weaknesses: ["Less depth than Deep Research for complex topics", "Not for reasoning-heavy analysis"],
        bestFor: ["Quick competitive scans", "News monitoring", "Fact-checking claims", "Market pricing research", "Pre-meeting account research"],
        costLabel: "$3 / $15 per 1M tokens",
        speed: "moderate",
        promptTip: "Include time constraints ('from the last 30 days'). Specify source types. Use follow-up questions to drill down iteratively.",
        keyBenchmark: "93.9% factuality; 200K context",
      },
    ],
    workflowTip: "Perplexity Deep Research for web-wide synthesis → NotebookLM Plus for internal doc analysis → Claude Opus to merge into a polished research memo.",
  },

  writing: {
    id: "writing",
    name: "Writing",
    weight: "17%",
    description: "Long-form content, reports, emails, decks, blog posts, marketing copy, technical docs, executive communications",
    topModels: [
      {
        rank: 1,
        modelName: "Claude Opus 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best professional writing — precise instruction-following + lowest hallucination produces polished, grounded long-form content",
        strengths: [
          "Best at following specific voice, tone, and style instructions",
          "Lowest hallucination keeps facts accurate in writing",
          "Exceptional long-form: memos, reports, white papers",
          "Best minimal-change editing (preserves author intent exactly)",
          "Cleanest, most structured prose output",
        ],
        weaknesses: ["Less creative spark than GPT-5.2 for pure fiction/narrative", "Slower and more expensive"],
        bestFor: ["Executive memos", "Investment reports", "White papers", "Technical documentation", "Legal-adjacent writing", "Board presentations"],
        costLabel: "$5 / $25 per 1M tokens",
        speed: "slow",
        promptTip: "Specify voice explicitly: 'Direct, confident, no jargon. Short paragraphs. Active voice.' Provide 1–2 example sentences that match your target style.",
        keyBenchmark: "Lowest hallucination rate among frontier models",
      },
      {
        rank: 2,
        modelName: "GPT-5.2 Thinking",
        provider: "OpenAI",
        accessVia: "chatgpt.com / API",
        verdict: "Best creative writing depth — strongest narrative voice, most compelling hooks, best at generating fresh angles",
        strengths: [
          "Strongest creative writing generator (68% market share)",
          "Best narrative voice, story structure, and compelling hooks",
          "Excellent at generating multiple creative directions simultaneously",
          "Strong analogies, metaphors, and persuasive rhetoric",
        ],
        weaknesses: ["Higher hallucination baseline than Claude", "Verbose by default — needs scope discipline"],
        bestFor: ["Blog posts", "Marketing copy", "Newsletter content", "Creative campaigns", "Storytelling", "Persuasive long-form"],
        costLabel: "High (subscription bundled)",
        speed: "moderate",
        promptTip: "CTCO format. Add scope discipline: 'Do not expand beyond the requested section.' Place critical style instructions at top AND bottom of prompt.",
        keyBenchmark: "~68% market share; industry-leading creative generation",
      },
      {
        rank: 3,
        modelName: "Claude Sonnet 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best daily writing workhorse — fast enough for real-time writing sessions, precise enough for professional output",
        strengths: [
          "3–5x faster than Opus for rapid content production",
          "Consistent voice and quality across long documents",
          "Strong instruction following for style guides",
          "Excellent iterative drafting partner",
        ],
        weaknesses: ["Less exhaustive than Opus for complex structured writing"],
        bestFor: ["Daily emails", "Slack messages", "Meeting summaries", "Short reports", "Social posts", "First drafts"],
        costLabel: "$3 / $15 per 1M tokens",
        speed: "moderate",
        promptTip: "Great for 'Draft → Critique → Refine' loops. Ask: 'Write a first draft, then list 3 ways to make it stronger before I review.'",
        keyBenchmark: "77.2% SWE-bench; best speed/quality ratio",
      },
      {
        rank: 4,
        modelName: "GPT-4.1",
        provider: "OpenAI",
        accessVia: "chatgpt.com / API",
        verdict: "Best for structured content at scale — reliable, fast, and excellent with templates, formats, and high-volume output",
        strengths: [
          "Precise structured output (JSON, markdown tables, numbered lists)",
          "1M context for long document series",
          "Fastest for high-volume content generation",
          "Reliable template adherence",
        ],
        weaknesses: ["No deep reasoning", "Less creative depth than GPT-5.2"],
        bestFor: ["Template-based content", "Email sequences", "FAQ generation", "Technical docs", "Content operations at scale"],
        costLabel: "Moderate",
        speed: "fast",
        promptTip: "Provide explicit template structure or schema. GPT-4.1 excels when you give it a format to fill rather than asking it to invent one.",
        keyBenchmark: "1M context; precise structured output",
      },
    ],
    workflowTip: "GPT-5.2 for a creative first draft → Claude Sonnet to tighten and structure → Claude Opus for final precision polish on high-stakes pieces.",
  },

  strategy: {
    id: "strategy",
    name: "Strategy",
    weight: "16%",
    description: "Business strategy, competitive analysis, scenario planning, investment thesis, market positioning, M&A rationale",
    topModels: [
      {
        rank: 1,
        modelName: "o3",
        provider: "OpenAI",
        accessVia: "chatgpt.com / API",
        verdict: "Best for strategy requiring deep deliberation — thinks through multiple scenarios, adversarial cases, and second-order effects before recommending",
        strengths: [
          "Extended deliberation surfaces second-order effects",
          "Best at multi-constraint scenario optimization",
          "Excellent at identifying strategic blind spots",
          "Strong adversarial analysis (what's the bear case?)",
          "Best for reasoning through complex tradeoffs",
        ],
        weaknesses: ["Slow", "Expensive", "Output can be verbose"],
        bestFor: ["Investment theses", "Go-to-market strategy", "Competitive response planning", "Risk-weighted decision analysis", "Multi-year strategic plans"],
        costLabel: "High (API)",
        speed: "slow",
        promptTip: "Ask: 'Before recommending, identify the 3 most common mistakes companies make in this situation, then give me your recommendation accounting for those.' Use reasoning_effort=high.",
        keyBenchmark: "State-of-the-art complex reasoning; 93.2% GPQA Diamond (Pro tier)",
      },
      {
        rank: 2,
        modelName: "Claude Opus 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best structured strategic frameworks — produces clean, usable Porter's 5 Forces, BCG matrices, and SWOT analyses with real depth",
        strengths: [
          "Follows strategic framework templates with precision",
          "Low hallucination keeps competitive intelligence grounded",
          "Best at multi-page strategy memos and board presentations",
          "1,606 Elo enterprise knowledge benchmark (#1)",
          "Excellent at structured argument and recommendation logic",
        ],
        weaknesses: ["Less creative divergent thinking than o3 for novel strategy"],
        bestFor: ["Strategy memos", "Framework analysis (Porter's, SWOT, BCG)", "Board presentations", "M&A rationale", "Market entry analysis"],
        costLabel: "$5 / $25 per 1M tokens",
        speed: "slow",
        promptTip: "Specify exact framework: 'Analyze using Porter's 5 Forces. Rate each force 1–10 and explain. End with a priority recommendation and 3 concrete next steps.'",
        keyBenchmark: "1,606 Elo GDPval-AA enterprise benchmark (#1)",
      },
      {
        rank: 3,
        modelName: "GPT-5.2 Pro",
        provider: "OpenAI",
        accessVia: "chatgpt.com (Pro subscription)",
        verdict: "Best for broad strategic intelligence — widest professional knowledge base enables cross-industry benchmarking and unconventional angles",
        strengths: [
          "70.9% GDPval across 44 professions (broadest coverage)",
          "93.2% GPQA Diamond professional-level reasoning",
          "Best cross-industry analogies and benchmarking",
          "Strong at generating unconventional strategic angles",
          "Widest exposure to business strategy literature",
        ],
        weaknesses: ["Most expensive", "Slowest response times", "Higher hallucination than Claude for specific facts"],
        bestFor: ["Cross-industry strategic benchmarking", "Novel market category creation", "Unconventional positioning strategies", "Emerging market analysis"],
        costLabel: "Highest (subscription bundled)",
        speed: "slowest",
        promptTip: "CTCO. Ask for multiple options before converging: 'Generate 5 strategic directions, then evaluate each against our constraints before recommending one.'",
        keyBenchmark: "93.2% GPQA Diamond; 70.9% GDPval-AA (44 professions)",
      },
    ],
    workflowTip: "Perplexity Deep Research for competitive landscape → o3 for deliberate scenario analysis → Claude Opus to structure into a polished strategy memo or board deck.",
  },

  image_video: {
    id: "image_video",
    name: "Image & Video Generation",
    weight: undefined,
    description: "AI image generation, video creation, visual content for marketing, social media, presentations, product demos",
    topModels: [
      {
        rank: 1,
        modelName: "Midjourney v7",
        provider: "Midjourney",
        accessVia: "midjourney.com (web) / Discord",
        verdict: "Best image quality — photorealistic, artistic, and commercial-grade output with unmatched aesthetic control and consistency",
        strengths: [
          "Best photorealistic output in the industry",
          "Strongest stylistic control (lighting, mood, camera angle)",
          "Fastest iteration with Vary, Zoom, and Region tools",
          "Best for commercial-grade marketing imagery",
          "Consistent character and brand style across generations",
        ],
        weaknesses: ["No direct API (Discord/web only)", "Text within images often unreliable", "Cannot precisely edit existing photos"],
        bestFor: ["Marketing hero images", "Brand imagery", "Social media visuals", "Product mockups", "Concept art", "Pitch deck visuals"],
        costLabel: "$10–$120/month (subscription tiers)",
        speed: "fast",
        promptTip: "Use modifiers: '--style raw' for photorealism, '--ar 16:9' for widescreen, '--v 7' for latest. Describe lighting, camera angle, and mood explicitly. Lead with the main subject.",
        keyBenchmark: "Industry-leading photorealism and aesthetic coherence",
      },
      {
        rank: 2,
        modelName: "Sora",
        provider: "OpenAI",
        accessVia: "sora.com (ChatGPT Pro subscribers)",
        verdict: "Best text-to-video — cinematic-quality video generation up to 1080p with complex scene understanding and temporal consistency",
        strengths: [
          "Up to 20s cinematic video from text prompt",
          "1080p output with temporal consistency",
          "Storyboarding and shot sequencing tools",
          "Blend, remix, and extend existing clips",
          "Understands camera movement and scene composition",
        ],
        weaknesses: ["ChatGPT Pro required ($200/month)", "Physics simulation occasionally fails", "Long generation times (minutes per clip)"],
        bestFor: ["Marketing videos", "Product demos", "Social media shorts", "Concept visualization", "Pitch deck animations", "Brand films"],
        costLabel: "$200/month (ChatGPT Pro) or API credits",
        speed: "slow",
        promptTip: "Write prompts like a film director: 'Drone shot flying over a modern city at golden hour, slow dolly forward, cinematic color grading, 4K.' Include camera movement, lighting, and pacing.",
        keyBenchmark: "Industry-leading text-to-video; 1080p cinematic output",
      },
      {
        rank: 3,
        modelName: "Runway Gen-3 Alpha",
        provider: "Runway",
        accessVia: "runwayml.com",
        verdict: "Best video editing + generation hybrid — adds motion to images, extends clips, and generates video from reference photos",
        strengths: [
          "Best image-to-video (motion from still photos)",
          "Video extension and inpainting tools",
          "Motion Brush (control motion of specific elements)",
          "Deployed by major film and advertising studios",
          "Strong camera control primitives",
        ],
        weaknesses: ["Max 10 seconds per generation", "Credits can be expensive at scale", "Less cinematic than Sora for pure text-to-video"],
        bestFor: ["Animating product images", "Video ads from photos", "Short-form social content", "Brand video creation", "B-roll generation", "Product 360 views"],
        costLabel: "$15–$95/month (subscription)",
        speed: "moderate",
        promptTip: "For image-to-video: use a clean, well-composed reference image. Specify motion: 'slow camera pull-back' or 'product rotating 360 degrees on white background.'",
        keyBenchmark: "Best image-to-video; Motion Brush control; studio-adopted",
      },
    ],
    workflowTip: "Midjourney for static marketing assets → Runway to add motion → Sora for full cinematic video scenes. Use DALL-E 3 (in ChatGPT) for quick concept iterations.",
  },

  quick_mvp: {
    id: "quick_mvp",
    name: "Quick MVP / Lovable / Bolt",
    weight: undefined,
    description: "Rapid prototyping, full-stack app scaffolding, AI-powered no-code/low-code tools for fast product builds and hackathon projects",
    topModels: [
      {
        rank: 1,
        modelName: "Claude Sonnet 4.5 (via Bolt.new / Cursor)",
        provider: "Anthropic + Bolt / Cursor",
        accessVia: "bolt.new / cursor.com",
        verdict: "Best full-stack scaffolding — 77.2% SWE-bench powers Bolt.new's top-tier code generation for complete working apps from a single prompt",
        strengths: [
          "Best coding quality in Bolt.new and Cursor",
          "Full-stack React/Next.js apps from natural language",
          "Precise instruction following for iterative feature builds",
          "200K context holds entire project in memory",
          "Handles auth, databases, and API integrations well",
        ],
        weaknesses: ["Bolt.new has file system and package limitations", "Complex apps may need manual refactoring", "React Native / mobile native less reliable"],
        bestFor: ["Landing pages", "SaaS dashboards", "CRM tools", "Internal tools", "MVP validation builds", "Hackathon projects"],
        costLabel: "$3 / $15 per 1M tokens (underlying); Bolt subscription separately",
        speed: "moderate",
        promptTip: "In Bolt: describe the full app in one detailed prompt first, then iterate. Include: tech stack, data models, key features, and design style. Specificity dramatically improves first-pass quality.",
        keyBenchmark: "77.2% SWE-bench; powers Bolt.new top-tier outputs",
      },
      {
        rank: 2,
        modelName: "GPT-4.1 (via Bolt.new / Lovable)",
        provider: "OpenAI + Bolt / Lovable",
        accessVia: "bolt.new / lovable.dev",
        verdict: "Best structured code output for no-code builders — 1M context holds the entire codebase in mind for consistent generation",
        strengths: [
          "1M token context (entire codebase fits)",
          "Reliable structured code with correct formatting",
          "Great with Lovable's visual builder integration",
          "Fast iteration speed for rapid feature additions",
          "Precise instruction following for component-level changes",
        ],
        weaknesses: ["No deep reasoning for complex architectural problems", "Less precise than Claude for nuanced requirements"],
        bestFor: ["Lovable.dev builds", "Template-based apps", "Quick CRUD applications", "Dashboard prototypes", "Form-heavy internal tools"],
        costLabel: "Moderate (via platform subscriptions)",
        speed: "fast",
        promptTip: "In Lovable: use the visual editor for layout, then switch to GPT-4.1 for custom logic. Great for: 'Add Stripe checkout' or 'Connect this form to Supabase.'",
        keyBenchmark: "1M token context; best structured output for builders",
      },
      {
        rank: 3,
        modelName: "Gemini 3 Flash (via Firebase Studio)",
        provider: "Google DeepMind + Firebase",
        accessVia: "firebase.studio",
        verdict: "Best Google-native prototyping — instant Firebase integration means auth, database, and hosting ship together from a single prompt",
        strengths: [
          "Native Firebase (auth, Firestore, Functions, Hosting) integration",
          "78% SWE-bench — fastest high-quality code generation",
          "Google Cloud deployment in one click",
          "Generous free tier for prototypes",
          "Best for realtime apps with Firebase's live sync",
        ],
        weaknesses: ["Firebase ecosystem lock-in", "Firebase Studio still limited access (waitlist)", "Less design polish than Lovable/Bolt"],
        bestFor: ["Firebase-backed apps", "Google ecosystem startups", "Realtime database apps", "Auth-heavy prototypes", "Apps with Google Maps / Analytics"],
        costLabel: "$0.50 / $3.00 per 1M tokens; Firebase costs separate",
        speed: "fastest",
        promptTip: "Start with a clear data model: 'Build a [app type] with Firestore collections [X, Y, Z], [auth providers], and [key features]. Deploy to Firebase Hosting.'",
        keyBenchmark: "78% SWE-bench; fastest code generation; native Firebase",
      },
    ],
    workflowTip: "Day 1: Bolt.new with Claude Sonnet for full-stack scaffolding → Day 2: Cursor for refinement and debugging → Deploy to Vercel (Next.js) or Firebase (Gemini Flash). Use Lovable for design-heavy MVPs.",
  },

  finance: {
    id: "finance",
    name: "Finance, Excel & Numbers",
    weight: undefined,
    description: "Financial modeling, spreadsheet automation, data analysis, quantitative reasoning, investment analysis, valuation, accounting",
    topModels: [
      {
        rank: 1,
        modelName: "o3",
        provider: "OpenAI",
        accessVia: "chatgpt.com / API",
        verdict: "Best quantitative reasoning — deliberate math-first thinking catches formula errors and logical inconsistencies lighter models miss",
        strengths: [
          "100% AIME 2025 — state-of-the-art mathematical reasoning",
          "Best at multi-step financial calculations with full audit trails",
          "Excellent at catching modeling errors and circular logic",
          "Strong DCF, LBO, and comps-based valuation",
          "Best for risk modeling and sensitivity analysis",
        ],
        weaknesses: ["Slow", "Expensive", "Overkill for simple Excel tasks"],
        bestFor: ["DCF and LBO models", "Complex financial forecasting", "Valuation analysis", "Option pricing", "Risk and scenario modeling", "Quantitative research"],
        costLabel: "High (API)",
        speed: "slow",
        promptTip: "Paste the raw numbers and model assumptions. Ask: 'Build a [model type] with these inputs. Show all assumptions explicitly. Flag any inputs that seem unusual relative to benchmarks.'",
        keyBenchmark: "100% AIME 2025; state-of-the-art mathematical reasoning",
      },
      {
        rank: 2,
        modelName: "GPT-5.2 Thinking + Code Interpreter",
        provider: "OpenAI",
        accessVia: "chatgpt.com (Advanced Data Analysis mode)",
        verdict: "Best Excel automation — Code Interpreter generates and executes live Python against your actual uploaded spreadsheets and returns real outputs",
        strengths: [
          "Runs Python code against your actual uploaded Excel/CSV files",
          "Generates cleaned Excel and CSV outputs directly",
          "Creates charts, pivot tables, and visualizations in-session",
          "Iterates on calculations in real-time with your data",
          "Can explain every step before executing",
        ],
        weaknesses: ["Requires file upload", "Session-based (resets on close)", "Edge case code errors possible"],
        bestFor: ["Excel automation", "CSV/spreadsheet cleaning and transformation", "Financial chart generation", "P&L analysis from raw exports", "Data normalization", "Automated reporting"],
        costLabel: "High (subscription bundled)",
        speed: "moderate",
        promptTip: "Upload your Excel/CSV directly. 'Clean this data, calculate [metrics], and produce a [chart type] with a summary table.' Ask it to explain its approach before running.",
        keyBenchmark: "Runs live Python; returns actual Excel and chart outputs",
      },
      {
        rank: 3,
        modelName: "Claude Opus 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best financial writing and analysis — #1 Finance Agent benchmark with lowest hallucination for fact-sensitive investor materials",
        strengths: [
          "#1 Finance Agent benchmark (GDPval-AA 1,606 Elo)",
          "Lowest hallucination keeps financial data grounded",
          "Best for investment memos, analyst reports, and investor materials",
          "Precise at following complex financial formatting requirements",
          "Excellent earnings call and financial statement analysis",
        ],
        weaknesses: ["Cannot execute code or manipulate files directly", "Slower than GPT for iterative calculation workflows"],
        bestFor: ["Investment memos", "Financial analysis writeups", "Earnings call summaries", "Portfolio review reports", "Investor updates", "Startup financial narratives"],
        costLabel: "$5 / $25 per 1M tokens",
        speed: "slow",
        promptTip: "Paste financial data in tables. 'Analyze this P&L and write an executive summary highlighting the 3 biggest opportunities and 2 risks. Audience: Series B investors.'",
        keyBenchmark: "#1 Finance Agent benchmark (GDPval-AA 1,606 Elo)",
      },
    ],
    workflowTip: "o3 for quantitative model building → GPT-5.2 + Code Interpreter for Excel automation and visualization → Claude Opus to write the investor memo or board report.",
  },

  legal: {
    id: "legal",
    name: "Legal & Lawyers",
    weight: undefined,
    description: "Contract review, legal research, document drafting, compliance analysis, regulatory interpretation, M&A due diligence",
    topModels: [
      {
        rank: 1,
        modelName: "Claude Opus 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best general legal AI — lowest hallucination rate is non-negotiable for legal work where a fabricated citation or wrong clause has real consequences",
        strengths: [
          "Lowest hallucination rate (critical for legal accuracy)",
          "Best at following precise legal formatting and structure instructions",
          "Excellent contract clause extraction and redlining",
          "1M token context (Opus 4.6) fits entire legal documents",
          "Best minimal-change editing that preserves legal intent",
        ],
        weaknesses: ["No real-time legal database access (Westlaw, LexisNexis)", "Cannot provide legal advice — always verify with licensed counsel"],
        bestFor: ["Contract review and redlining", "Legal document drafting", "Compliance checklists", "Policy analysis", "NDA review", "Term sheet analysis", "Legal memo structure"],
        costLabel: "$5 / $25 per 1M tokens",
        speed: "slow",
        promptTip: "Provide the full contract text and jurisdiction. 'Review this [contract type]: (1) flag high-risk clauses with severity, (2) identify missing standard protections, (3) suggest specific redline language for each issue.'",
        keyBenchmark: "Lowest hallucination rate; best minimal-change editing",
      },
      {
        rank: 2,
        modelName: "GPT-5.2 Pro",
        provider: "OpenAI",
        accessVia: "chatgpt.com (Pro subscription)",
        verdict: "Best for legal research and broad legal knowledge — 93.2% GPQA Diamond reflects deep professional knowledge across legal domains and jurisdictions",
        strengths: [
          "Broad legal knowledge across jurisdictions and practice areas",
          "93.2% GPQA Diamond — professional-level reasoning",
          "Excellent synthesis of complex legal frameworks",
          "Strong at identifying legal principles and analogous precedents",
          "Best cross-jurisdictional comparison",
        ],
        weaknesses: ["Higher hallucination than Claude — verify all specific citations", "No native Westlaw/LexisNexis integration"],
        bestFor: ["Legal research memos", "Regulatory analysis", "Cross-jurisdictional comparison", "Statutory interpretation", "Legal strategy brainstorming", "Framework explanation"],
        costLabel: "Highest (subscription bundled)",
        speed: "slowest",
        promptTip: "CTCO format. Always end with: 'Flag any claims that require verification from primary sources.' Never rely on specific case citations without independently checking.",
        keyBenchmark: "93.2% GPQA Diamond; broadest professional legal knowledge",
      },
      {
        rank: 3,
        modelName: "Harvey AI",
        provider: "Harvey",
        accessVia: "harvey.ai (enterprise license)",
        verdict: "Best purpose-built legal AI — trained on legal corpora, integrated with Westlaw and LexisNexis, deployed by Allen & Overy, PwC Legal, and major BigLaw firms",
        strengths: [
          "Trained specifically on legal data and workflows",
          "Native Westlaw and LexisNexis integration",
          "Deployed by Allen & Overy, PwC Legal, leading BigLaw firms",
          "Built for attorney workflows: document review, due diligence, drafting",
          "SOC 2 compliant; client data never used for training",
          "Playbook mode with firm-standard positions",
        ],
        weaknesses: ["Enterprise pricing (not consumer-accessible)", "Requires firm or organization license", "Less flexible for non-legal tasks"],
        bestFor: ["Large-scale document review", "M&A due diligence", "Regulatory filings", "Legal research with verified citations", "Production law firm workflows"],
        costLabel: "Enterprise (contact for pricing)",
        speed: "fast",
        promptTip: "Use Harvey's built-in legal templates and Playbook mode for contract review using your firm's standard positions. Best used through their interface, not via API.",
        keyBenchmark: "Purpose-built; Allen & Overy, PwC Legal, BigLaw deployed",
      },
    ],
    workflowTip: "Claude Opus for initial contract review and redlining → GPT-5.2 Pro for legal research context → Harvey AI for production-grade document review at scale (enterprise). Always have licensed counsel review final output.",
  },

  bd_gtm: {
    id: "bd_gtm",
    name: "BD, GTM & Business Development",
    weight: undefined,
    description: "Business development, pipeline management, email outreach, go-to-market strategy, content development, sales enablement, partner development",
    topModels: [
      {
        rank: 1,
        modelName: "GPT-4.1",
        provider: "OpenAI",
        accessVia: "chatgpt.com / API",
        verdict: "Best BD content engine — fast, reliable, and excellent at generating personalized email sequences, GTM content, and sales materials at scale",
        strengths: [
          "1M context for long prospect lists and full CRM context",
          "Precise structured output for email sequences and playbooks",
          "Fast iteration for A/B testing copy variants",
          "Excellent personalization from ICP details",
          "Best for GTM content calendars and sales battlecards",
        ],
        weaknesses: ["No deep reasoning for complex strategic BD", "Less creative depth for thought leadership content"],
        bestFor: ["Cold email sequences", "LinkedIn outreach templates", "CRM data enrichment", "GTM content calendar", "Sales battlecards", "Partnership proposals", "Email nurture campaigns"],
        costLabel: "Moderate",
        speed: "fast",
        promptTip: "CTCO. Include ICP details and company context. 'Write 5 cold email variations for [ICP], each using a different hook: problem-led, social proof, insight, question, bold claim.'",
        keyBenchmark: "1M context; best structured content output at scale",
      },
      {
        rank: 2,
        modelName: "Claude Sonnet 4.5",
        provider: "Anthropic",
        accessVia: "claude.ai / API",
        verdict: "Best BD strategy and proposal content — precise professional tone matches enterprise buyer expectations and elevates deal quality",
        strengths: [
          "Professional, precise B2B voice that matches enterprise expectations",
          "Best proposal and RFP response writing",
          "Strong competitive positioning and differentiation content",
          "Excellent for thought leadership (case studies, whitepapers)",
          "Consistent quality across long BD document sets",
        ],
        weaknesses: ["Slightly slower than GPT-4.1 for high-volume iteration"],
        bestFor: ["Proposal and RFP responses", "Case study writing", "Competitive analysis docs", "Partner deck content", "Executive sponsor comms", "Thought leadership articles"],
        costLabel: "$3 / $15 per 1M tokens",
        speed: "moderate",
        promptTip: "XML format with ICP, company context, and desired outcome. 'Write a [doc type] for [audience]. Our differentiators: [X]. Buyer's main concern: [Y]. Tone: direct and confident.'",
        keyBenchmark: "77.2% SWE-bench; best professional tone precision",
      },
      {
        rank: 3,
        modelName: "Perplexity Sonar Pro",
        provider: "Perplexity AI",
        accessVia: "perplexity.ai",
        verdict: "Best GTM market intelligence — real-time competitive data with citations for informed targeting, positioning, and account-level research",
        strengths: [
          "Real-time market and competitive intelligence with citations",
          "93.9% factuality for reliable strategic data",
          "Excellent TAM/SAM/SOM market sizing research",
          "Best for account-level pre-call intelligence",
          "Tracks funding, news, and leadership changes in real-time",
        ],
        weaknesses: ["Cannot generate outreach content directly", "Not for creative writing or strategy synthesis"],
        bestFor: ["Prospect account research", "Competitive intelligence for sales calls", "Market sizing", "Industry trend analysis for GTM narratives", "Conference and ICP research"],
        costLabel: "$3 / $15 per 1M tokens",
        speed: "moderate",
        promptTip: "Pre-call research: 'Give me the latest news, funding, and strategic priorities for [company]. Include key executive changes and press releases from the last 90 days.'",
        keyBenchmark: "93.9% factuality; real-time web research with citations",
      },
    ],
    workflowTip: "Perplexity Sonar Pro for account and market intelligence → Claude Sonnet for strategy memos and proposals → GPT-4.1 for outreach sequences and GTM content production at scale.",
  },
};

export function getAllModels(): { platform: Platform; model: string; entry: PlatformInfo["models"][0] }[] {
  const result: { platform: Platform; model: string; entry: PlatformInfo["models"][0] }[] = [];
  for (const [platformId, platform] of Object.entries(PLATFORMS)) {
    for (const model of platform.models) {
      result.push({ platform: platformId as Platform, model: model.name, entry: model });
    }
  }
  return result;
}

export function getModel(platform: Platform, modelName: string) {
  return PLATFORMS[platform]?.models.find((m) => m.name === modelName);
}

export function getPlatform(platform: Platform) {
  return PLATFORMS[platform];
}
